# Generated by Django 3.2.5 on 2022-05-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verifer',
            field=models.BooleanField(default=False, verbose_name='verifier'),
        ),
    ]
