# Generated by Django 3.2.5 on 2021-07-14 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import participant_profile.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participant_profile', '0002_auto_20210709_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(db_index=True, default=False, verbose_name='Verifikasi')),
                ('payment', models.FileField(upload_to=participant_profile.models.user_directory_path, verbose_name='Upload Bukti Pembayaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
