# Generated by Django 3.2.5 on 2021-08-08 03:55

from django.db import migrations, models
import participant_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0003_paymentupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfile',
            name='birth_cert',
            field=models.FileField(blank=True, null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Akta Kelahiran'),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='good_behave_cert',
            field=models.FileField(blank=True, null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Surat Kelakukan Baik'),
        ),
    ]
