# Generated by Django 3.2.5 on 2021-08-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0004_auto_20210808_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='city_born',
            field=models.CharField(db_index=True, help_text='Contoh: Kabupaten Bandung', max_length=100, verbose_name='Kota Tempat Lahir'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='date_born',
            field=models.DateField(db_index=True, verbose_name='Tanggal Lahir'),
        ),
    ]
