# Generated by Django 3.2.5 on 2021-08-12 04:02

from django.db import migrations, models
import participant_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0005_auto_20210808_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfile',
            name='family_cert',
            field=models.FileField(blank=True, null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Kartu Keluarga'),
        ),
    ]
