# Generated by Django 3.2.5 on 2021-08-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0006_studentfile_family_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorstudent',
            name='info',
            field=models.CharField(choices=[('WEB', 'Website'), ('IG', 'Instagram'), ('FB', 'Facebook'), ('TW', 'Twitter'), ('TK', 'Tiktok'), ('SDR', 'Sodara/Keluarga'), ('ALK', 'Alumni SMK Telkom'), ('ALS', 'Alumni SMP'), ('GMP', 'Guru SMP'), ('GRK', 'Guru SMK'), ('BRS', 'Brosur'), ('RDO', 'Radio'), ('LLY', 'Lainnya')], max_length=3, verbose_name='Info Primaseru (PPDB)'),
        ),
    ]
