# Generated by Django 3.2.5 on 2021-08-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0008_remove_majorstudent_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorstudent',
            name='enter_smk',
            field=models.CharField(choices=[('ORT', 'Orang Tua'), ('SDR', 'Sendiri'), ('ODS', 'Orang Tua dan Sendiri')], max_length=4, null=True, verbose_name='Keinginan Siapa Masuk SMK'),
        ),
    ]
