# Generated by Django 3.2.5 on 2021-08-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0009_majorstudent_enter_smk'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorstudent',
            name='charity',
            field=models.CharField(choices=[('0', 'Rp. 0'), ('25', 'Rp. 250.000,-'), ('50', 'Rp. 500.000,-'), ('150', 'Rp. 1.500.000,-'), ('200', 'Rp. 2.000.000,-'), ('250', 'Rp. 2.500.000,-'), ('300', 'Rp. 3.000.000,-')], max_length=4, null=True, verbose_name='Dana Sukarela'),
        ),
    ]
