# Generated by Django 3.2.5 on 2021-08-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0010_majorstudent_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorstudent',
            name='charity',
            field=models.CharField(choices=[('0', 'Rp. 0'), ('25', 'Rp. 250.000,-'), ('50', 'Rp. 500.000,-'), ('150', 'Rp. 1.500.000,-'), ('200', 'Rp. 2.000.000,-'), ('250', 'Rp. 2.500.000,-'), ('300', 'Rp. 3.000.000,-')], help_text='Dana Sukarela nantinya akan dimanfaatkan untuk pengembangan siswa dibidang non akademik (kompetisi dan perlombaan-perlombaan).', max_length=4, null=True, verbose_name='Dana Sukarela'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='achievement',
            field=models.TextField(blank=True, help_text='Contoh: Juara 1 Lomba Basket Tingkat Nasional', null=True, verbose_name='Prestasi yang Pernah diraih'),
        ),
    ]
