# Generated by Django 3.2.5 on 2021-08-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0012_auto_20210823_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantfamilycert',
            name='verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
