# Generated by Django 3.2.5 on 2021-08-24 03:47

from django.db import migrations, models
import participant_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0013_participantfamilycert_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfile',
            name='birth_cert',
        ),
        migrations.AddField(
            model_name='participantfamilycert',
            name='birth_cert',
            field=models.FileField(blank=True, null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Akta Kelahiran'),
        ),
    ]
