# Generated by Django 3.2.5 on 2021-08-24 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import participant_profile.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participant_profile', '0014_auto_20210824_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfile',
            name='ra_sem_1',
        ),
        migrations.RemoveField(
            model_name='studentfile',
            name='ra_sem_2',
        ),
        migrations.RemoveField(
            model_name='studentfile',
            name='ra_sem_3',
        ),
        migrations.RemoveField(
            model_name='studentfile',
            name='ra_sem_4',
        ),
        migrations.RemoveField(
            model_name='studentfile',
            name='ra_sem_5',
        ),
        migrations.AlterField(
            model_name='participantfamilycert',
            name='birth_cert',
            field=models.FileField(null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Akta Kelahiran'),
        ),
        migrations.AlterField(
            model_name='participantfamilycert',
            name='family_cert',
            field=models.FileField(null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Kartu Keluarga'),
        ),
        migrations.CreateModel(
            name='ReportFileParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('raport', models.FileField(null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Raport')),
                ('semester', models.CharField(choices=[('SEM_1', 'Semester 1'), ('SEM_2', 'Semester 2'), ('SEM_3', 'Semester 3'), ('SEM_4', 'Semester 4'), ('SEM_5', 'Semester 5')], help_text='Pilih raport semester berapa yang di unggah.', max_length=5, verbose_name='Semester Semester')),
                ('part', models.CharField(choices=[('P_1', 'Bagian 1'), ('P_2', 'Bagian 2'), ('P_3', 'Bagian 3')], help_text='Pilih bagian ke berapa raport yang di unggah.', max_length=3, verbose_name='Bagian')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
