# Generated by Django 3.2.5 on 2021-08-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0016_auto_20210825_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfileparticipant',
            name='part',
            field=models.CharField(choices=[('P_1', 'Bagian 1'), ('P_2', 'Bagian 2'), ('P_3', 'Bagian 3')], help_text='Pilih bagian ke berapa raport yang di unggah.', max_length=3, verbose_name='Bagian Raport'),
        ),
        migrations.AlterField(
            model_name='reportfileparticipant',
            name='semester',
            field=models.CharField(choices=[('SEM_1', 'Semester 1'), ('SEM_2', 'Semester 2'), ('SEM_3', 'Semester 3'), ('SEM_4', 'Semester 4'), ('SEM_5', 'Semester 5')], help_text='Pilih raport semester berapa yang di unggah.', max_length=5, verbose_name='Raport Semester'),
        ),
    ]
