# Generated by Django 3.2.5 on 2021-08-27 07:49

from django.db import migrations, models
import participant_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0018_alter_reportfileparticipant_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprofile',
            name='image',
            field=models.ImageField(default='default_photo.png', upload_to=participant_profile.models.user_directory_path, verbose_name='Photo'),
        ),
    ]
