# Generated by Django 3.2.5 on 2021-08-30 02:35

from django.db import migrations, models
import participant_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0020_alter_majorstudent_charity'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfile',
            name='ijazah',
            field=models.FileField(blank=True, null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Ijazah'),
        ),
    ]
