# Generated by Django 3.2.5 on 2021-08-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0021_studentfile_ijazah'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorstudent',
            name='way_in',
            field=models.CharField(choices=[('JP', 'Jalur Prestasi'), ('JR1', 'Jalur Reguler 1'), ('JR2', 'Jalur Reguler 2'), ('JR3', 'Jalur Reguler 3')], max_length=3, null=True, verbose_name='Jalur Masuk'),
        ),
    ]
