# Generated by Django 3.2.5 on 2021-08-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0022_majorstudent_way_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorstudent',
            name='charity',
            field=models.CharField(choices=[('0', 'Rp. 0'), ('Rp. 500.000,-', 'Rp. 500.000,-'), ('Rp. 1.000.000,-', 'Rp. 1.000.000,-'), ('Rp. 1.500.000,-', 'Rp. 1.500.000,-'), ('Rp. 2.000.000,-', 'Rp. 2.000.000,-'), ('Rp. 2.500.000,-', 'Rp. 2.500.000,-'), ('Rp. 3.000.000,-', 'Rp. 3.000.000,-')], help_text='Dana Sukarela nantinya akan dimanfaatkan untuk pengembangan siswa dibidang non akademik (kompetisi dan perlombaan-perlombaan).', max_length=20, null=True, verbose_name='Dana Sukarela'),
        ),
        migrations.AlterField(
            model_name='majorstudent',
            name='enter_smk',
            field=models.CharField(choices=[('Orang Tua', 'Orang Tua'), ('Sendiri', 'Sendiri'), ('Orang Tua dan Sendiri', 'Orang Tua dan Sendiri')], max_length=25, null=True, verbose_name='Keinginan Siapa Masuk SMK'),
        ),
        migrations.AlterField(
            model_name='majorstudent',
            name='way_in',
            field=models.CharField(choices=[('Jalur Prestasi', 'Jalur Prestasi'), ('Jalur Reguler 1', 'Jalur Reguler 1'), ('Jalur Reguler 2', 'Jalur Reguler 2'), ('Jalur Reguler 3', 'Jalur Reguler 3')], max_length=20, null=True, verbose_name='Jalur Masuk'),
        ),
    ]
