# Generated by Django 3.2.5 on 2021-08-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0024_auto_20210830_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majorstudent',
            options={'ordering': ['participant']},
        ),
        migrations.AlterModelOptions(
            name='participantfamilycert',
            options={'ordering': ['participant']},
        ),
        migrations.AlterModelOptions(
            name='participantprofile',
            options={'ordering': ['participant']},
        ),
        migrations.AlterModelOptions(
            name='paymentupload',
            options={'ordering': ['participant']},
        ),
        migrations.AlterModelOptions(
            name='photoprofile',
            options={'ordering': ['participant']},
        ),
        migrations.AlterModelOptions(
            name='reportfileparticipant',
            options={'ordering': ['participant']},
        ),
        migrations.AlterModelOptions(
            name='studentfile',
            options={'ordering': ['participant']},
        ),
    ]
