# Generated by Django 3.2.5 on 2021-09-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0026_auto_20210901_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatherstudentprofile',
            name='nik',
            field=models.CharField(help_text='Diisi berdasarkan Kartu Keluarga', max_length=20, null=True, verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
        migrations.AlterField(
            model_name='motherstudentprofile',
            name='nik',
            field=models.CharField(help_text='Diisi berdasarkan Kartu Keluarga', max_length=20, null=True, verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='nik',
            field=models.CharField(help_text='Bisa dicek di Kartu Keluarga', max_length=20, unique=True, verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
        migrations.AlterField(
            model_name='studentguardianprofile',
            name='nik',
            field=models.CharField(help_text='Diisi berdasarkan Kartu Keluarga', max_length=20, null=True, verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
    ]
