# Generated by Django 3.2.5 on 2021-09-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0027_auto_20210903_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='kk_number',
            field=models.CharField(help_text='Diisi berdasarkan Kartu Keluarga', max_length=20, verbose_name='Nomor Kartu Keluarga (KK)'),
        ),
    ]
