# Generated by Django 3.2.5 on 2021-09-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0028_alter_participantprofile_kk_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatherstudentprofile',
            name='job',
            field=models.CharField(max_length=100, null=True, verbose_name='Pekerjaan'),
        ),
        migrations.AlterField(
            model_name='fatherstudentprofile',
            name='salary',
            field=models.PositiveIntegerField(help_text='Diisi dengan angka', null=True, verbose_name='Penghasilan'),
        ),
        migrations.AlterField(
            model_name='motherstudentprofile',
            name='job',
            field=models.CharField(max_length=100, null=True, verbose_name='Pekerjaan'),
        ),
        migrations.AlterField(
            model_name='motherstudentprofile',
            name='salary',
            field=models.PositiveIntegerField(help_text='Diisi dengan angka', null=True, verbose_name='Penghasilan'),
        ),
        migrations.AlterField(
            model_name='studentguardianprofile',
            name='job',
            field=models.CharField(max_length=100, null=True, verbose_name='Pekerjaan'),
        ),
        migrations.AlterField(
            model_name='studentguardianprofile',
            name='salary',
            field=models.PositiveIntegerField(help_text='Diisi dengan angka', null=True, verbose_name='Penghasilan'),
        ),
    ]
