# Generated by Django 3.2.5 on 2021-09-12 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import participant_profile.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participant_profile', '0029_auto_20210903_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorstudent',
            name='first_major',
            field=models.CharField(choices=[('TKJ', 'Teknik Komputer dan Jaringan'), ('TJAT', 'Teknik Jaringan Akses Telekomunikasi'), ('MM', 'Multimedia')], max_length=4, verbose_name='Pilihan Jurusan Pertama'),
        ),
        migrations.AlterField(
            model_name='majorstudent',
            name='second_major',
            field=models.CharField(choices=[('TKJ', 'Teknik Komputer dan Jaringan'), ('TJAT', 'Teknik Jaringan Akses Telekomunikasi'), ('MM', 'Multimedia')], max_length=4, verbose_name='Pilihan Jurusan Kedua'),
        ),
        migrations.CreateModel(
            name='ParticipantCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(upload_to=participant_profile.models.user_directory_path, verbose_name='Sertifikat Penghargaan')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['participant'],
            },
        ),
    ]
