# Generated by Django 3.2.5 on 2021-09-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0030_auto_20210912_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantcert',
            name='certi_name',
            field=models.CharField(help_text='Tuliskan beserta nomor Juara', max_length=120, null=True, verbose_name='Nama Sertifikat'),
        ),
        migrations.AddField(
            model_name='participantcert',
            name='level',
            field=models.CharField(help_text='Tuliskan tingkat lomba, contoh: Tingkat Kabupaten', max_length=100, null=True, verbose_name='Lomba Tingkat'),
        ),
    ]
