# Generated by Django 3.2.5 on 2021-09-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0032_participantcert_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantcert',
            name='level',
        ),
    ]
