# Generated by Django 3.2.5 on 2021-09-14 10:56

from django.db import migrations, models
import participant_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0033_remove_participantcert_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfile',
            name='ijazah_elem',
            field=models.FileField(blank=True, help_text='Ijazah dapat menyusul.', null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Ijazah SD'),
        ),
    ]
