# Generated by Django 3.2.5 on 2021-09-15 08:32

from django.db import migrations, models
import participant_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0034_studentfile_ijazah_elem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfileparticipant',
            name='part',
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='ijazah',
            field=models.FileField(blank=True, help_text='Ijazah dapat menyusul.', null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Ijazah SMP/MTS'),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='ijazah_elem',
            field=models.FileField(blank=True, help_text='Ijazah dapat menyusul.', null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Ijazah SD/MI'),
        ),
    ]
