# Generated by Django 3.2.5 on 2021-09-21 02:12

from django.db import migrations, models
import participant_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0035_auto_20210915_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfile',
            name='color_blind_cert',
            field=models.FileField(null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Surat Keterangan Tidak Buta Warna'),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='good_behave_cert',
            field=models.FileField(null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Surat Kelakukan Baik'),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='healty_cert',
            field=models.FileField(null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Surat Keterangan Sehat'),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='ijazah',
            field=models.FileField(help_text='Ijazah SMP/MTS dapat menyusul.', null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Ijazah SMP/MTS'),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='ijazah_elem',
            field=models.FileField(null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Ijazah SD/MI'),
        ),
    ]
