# Generated by Django 3.2.5 on 2021-09-21 02:13

from django.db import migrations, models
import participant_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0036_auto_20210921_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfile',
            name='ijazah',
            field=models.FileField(blank=True, help_text='Ijazah SMP/MTS dapat menyusul.', null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Ijazah SMP/MTS'),
        ),
    ]
