# Generated by Django 3.2.5 on 2021-09-27 04:27

from django.db import migrations, models
import participant_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0037_alter_studentfile_ijazah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfile',
            name='good_behave_cert',
            field=models.FileField(blank=True, null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Surat Kelakukan Baik'),
        ),
    ]
