# Generated by Django 3.2.5 on 2021-10-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0038_alter_studentfile_good_behave_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='nisn',
            field=models.CharField(help_text='Isi NISN berdasarkan NISN yang diberikan sewaktu SMP.', max_length=20, unique=True, verbose_name='NISN'),
        ),
    ]
