# Generated by Django 3.2.5 on 2021-12-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0040_auto_20211117_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorstudent',
            name='color_blind',
            field=models.CharField(choices=[('N', 'Tidak'), ('YP', 'Ya, Buta Warna Parsial (Sebagian)'), ('YT', 'Ya, Buta Warna Total')], default='N', help_text='Apakah anda buta warna?', max_length=2, verbose_name='Buta Warna'),
        ),
    ]
