# Generated by Django 3.2.11 on 2022-01-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0041_majorstudent_color_blind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfileparticipant',
            name='semester',
            field=models.CharField(choices=[('SEM_1', 'Semester 1'), ('SEM_2', 'Semester 2'), ('SEM_3', 'Semester 3'), ('SEM_4', 'Semester 4'), ('SEM_5', 'Semester 5')], help_text='Pilih raport semester berapa yang di unggah.', max_length=5, verbose_name='Raport Semester'),
        ),
    ]
