# Generated by Django 3.2.11 on 2022-02-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0042_alter_reportfileparticipant_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatherstudentprofile',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, null=True, verbose_name='No. HP'),
        ),
        migrations.AlterField(
            model_name='motherstudentprofile',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, null=True, verbose_name='No. HP'),
        ),
        migrations.AlterField(
            model_name='studentguardianprofile',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, null=True, verbose_name='No. HP'),
        ),
    ]
