# Generated by Django 3.2.13 on 2022-08-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0043_auto_20220203_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='resident',
            field=models.CharField(choices=[('Bersama Orang Tua', 'Bersama Orang Tua'), ('Kost', 'Kost'), ('Asrama', 'Asrama'), ('Kontrak', 'Kontrak'), ('Bersama Wali', 'Bersama Wali')], help_text='Contoh: Rumah Pribadi, Kost, Rumah Keluarga (Keluarga Besar)', max_length=50, verbose_name='Tempat Tinggal'),
        ),
    ]
