# Generated by Django 3.2.13 on 2022-08-23 04:33

from django.db import migrations, models
import participant_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0045_auto_20220823_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantprofile',
            name='relatives_no',
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='siblings_no',
            field=models.CharField(help_text='Masukan jumlah saudara Anda (<b> isi hanya dengan angka </b>)', max_length=2, null=True, validators=[participant_profile.models.validate_two_digits_num], verbose_name='Dari Berapa Bersaudara'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='child_no',
            field=models.CharField(help_text='Masukan kamu anak ke berapa. Contoh: Anak ke 2 (<b>isi hanya dengan angka</b>)', max_length=2, null=True, validators=[participant_profile.models.validate_two_digits_num], verbose_name='Anak Ke-'),
        ),
    ]
