# Generated by Django 3.2.13 on 2022-09-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0046_auto_20220823_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorstudent',
            name='first_major',
            field=models.CharField(choices=[('TJKT', 'Teknik Jaringan Komputer dan Telekomunikasi'), ('DKV', 'Desain Komunikasi & Visual'), ('Animasi', 'Animasi')], max_length=10, verbose_name='Pilihan Jurusan Pertama'),
        ),
        migrations.AlterField(
            model_name='majorstudent',
            name='second_major',
            field=models.CharField(choices=[('TJKT', 'Teknik Jaringan Komputer dan Telekomunikasi'), ('DKV', 'Desain Komunikasi & Visual'), ('Animasi', 'Animasi')], max_length=10, verbose_name='Pilihan Jurusan Kedua'),
        ),
    ]
