# Generated by Django 3.2.13 on 2022-11-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_profile', '0047_auto_20220916_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorstudent',
            name='first_major',
            field=models.CharField(choices=[('TJKT', 'Teknik Jaringan Komputer dan Telekomunikasi'), ('DKV', 'Desain Komunikasi & Visual'), ('ANI', 'Animasi')], max_length=10, verbose_name='Pilihan Jurusan Pertama'),
        ),
        migrations.AlterField(
            model_name='majorstudent',
            name='second_major',
            field=models.CharField(choices=[('TJKT', 'Teknik Jaringan Komputer dan Telekomunikasi'), ('DKV', 'Desain Komunikasi & Visual'), ('ANI', 'Animasi')], max_length=10, verbose_name='Pilihan Jurusan Kedua'),
        ),
        migrations.AlterField(
            model_name='majorstudent',
            name='way_in',
            field=models.CharField(choices=[('Jalur Prestasi', 'Jalur Prestasi'), ('Jalur Reguler', 'Jalur Reguler'), ('Jalur Reguler 1', 'Jalur Reguler 1'), ('Jalur Reguler 2', 'Jalur Reguler 2'), ('Jalur Reguler 3', 'Jalur Reguler 3')], max_length=20, null=True, verbose_name='Jalur Masuk'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='npsn_school_origin',
            field=models.PositiveIntegerField(help_text="Bisa Cek <a href='https://referensi.data.kemdikbud.go.id/pendidikan/dikdas' target='_blank'><b>Disini</b></a>", null=True, verbose_name='Nomor NPSN Sekolah Asal'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='school_origin',
            field=models.CharField(help_text='Isilah sesuai dengan asal sekolah Anda dan dituliskan seperti contoh berikut : SMP Telkom Bandung ', max_length=120, verbose_name='Asal Sekolah'),
        ),
    ]
