# Generated by Django 3.2.5 on 2021-07-07 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('registration_number', models.IntegerField(db_index=True, unique=True, verbose_name='Registration Number')),
                ('participant_phone_number', models.IntegerField(verbose_name='Participant Phone Number')),
                ('homeroom_teacher_phone_number', models.IntegerField(verbose_name='Homeroom Teacher Phone Number')),
                ('parent_full_name', models.CharField(max_length=100, verbose_name='Parent Full Name')),
                ('representative', models.CharField(choices=[('B', 'Bapak'), ('I', 'Ibu'), ('W', 'Wali')], max_length=1, verbose_name='Representative')),
                ('parent_phone_number', models.IntegerField(verbose_name='Parent Phone Number')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
