# Generated by Django 3.2.5 on 2021-07-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='homeroom_teacher_phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Homeroom Teacher Phone Number'),
        ),
    ]
