# Generated by Django 3.2.5 on 2021-07-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_participant_homeroom_teacher_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField(db_index=True)),
            ],
        ),
    ]
