# Generated by Django 3.2.5 on 2021-07-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_participantcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantcount',
            name='count',
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
