# Generated by Django 3.2.5 on 2021-07-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_participantcount_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nama Gelombang Pendaftaran')),
                ('start_date', models.DateField(verbose_name='Tanggal Dimulai Pendaftaran')),
                ('end_date', models.DateField(verbose_name='Tanggal Berakhir Pendaftaran')),
            ],
        ),
    ]
