# Generated by Django 3.2.5 on 2021-07-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_registerschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100, verbose_name='Langkap Pendaftaran')),
                ('icon', models.ImageField(upload_to='register_step_icon', verbose_name='Icon')),
            ],
        ),
    ]
