# Generated by Django 3.2.5 on 2021-07-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_registerstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='homeroom_teacher_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Homeroom Teacher Phone Number'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='parent_phone_number',
            field=models.CharField(max_length=15, verbose_name='Parent Phone Number'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_phone_number',
            field=models.CharField(max_length=15, verbose_name='Participant Phone Number'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registration_number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Registration Number'),
        ),
    ]
