# Generated by Django 3.2.5 on 2021-07-14 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0008_participantgraduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantgraduation',
            name='chose_major',
            field=models.CharField(choices=[('TKJ', 'Teknik Komputer dan Jaringan'), ('TJAT', 'Teknik Jaringan Akses dan Telekomunikasi'), ('MM', 'Multimedia')], max_length=4, verbose_name='Diterima di Jurusan:'),
        ),
        migrations.AlterField(
            model_name='participantgraduation',
            name='letter',
            field=models.FileField(blank=True, null=True, upload_to='berkas_kelulusan/', verbose_name='Surat Kelulusan'),
        ),
        migrations.CreateModel(
            name='ParticipantLMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, verbose_name='Username')),
                ('password', models.CharField(max_length=120, verbose_name='Password')),
                ('schedule', models.DateField(verbose_name='Tanggal')),
                ('time', models.CharField(max_length=6, verbose_name='Waktu')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
