# Generated by Django 3.2.5 on 2021-07-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210714_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantlms',
            name='time',
            field=models.CharField(max_length=6, verbose_name='Pukul'),
        ),
    ]
