# Generated by Django 3.2.5 on 2021-07-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_participantgraduation_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantgraduation',
            name='chose_major',
            field=models.CharField(blank=True, choices=[('TKJ', 'Teknik Komputer dan Jaringan'), ('TJAT', 'Teknik Jaringan Akses dan Telekomunikasi'), ('MM', 'Multimedia')], max_length=4, null=True, verbose_name='Diterima di Jurusan:'),
        ),
    ]
