# Generated by Django 3.2.5 on 2021-07-23 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_participantgraduation_chose_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='parent_full_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='representative',
        ),
    ]
