# Generated by Django 3.2.5 on 2021-07-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210723_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerstep',
            name='icon',
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='homeroom_teacher_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='No. HP Wali Kelas'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='parent_phone_number',
            field=models.CharField(max_length=15, verbose_name='No. HP Orang Tua/Wali'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_phone_number',
            field=models.CharField(max_length=15, verbose_name='No. HP Calon Siswa'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registration_number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Nomor Pendaftaran'),
        ),
    ]
