# Generated by Django 3.2.5 on 2021-08-08 03:24

from django.db import migrations, models
import participant_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20210727_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='family_card',
            field=models.FileField(null=True, upload_to=participant_profile.models.user_directory_path, verbose_name='Kartu Keluarga'),
        ),
    ]
