# Generated by Django 3.2.5 on 2021-08-08 03:55

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_participant_family_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='family_card',
            field=models.FileField(null=True, upload_to=dashboard.models.user_directory_path, verbose_name='Kartu Keluarga'),
        ),
    ]
