# Generated by Django 3.2.5 on 2021-08-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_participant_family_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='family_card',
        ),
        migrations.AddField(
            model_name='participant',
            name='bk_teacher_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='No. HP Guru BK'),
        ),
        migrations.AddField(
            model_name='participant',
            name='parnet_full_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nama Lengkap Orang Tua'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registration_number',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True, verbose_name='Nomor Pendaftaran'),
        ),
    ]
