# Generated by Django 3.2.5 on 2021-08-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_parnet_full_name_participant_parent_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Verified'),
        ),
    ]
