# Generated by Django 3.2.5 on 2021-08-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_participant_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_phone_number',
            field=models.CharField(db_index=True, max_length=15, unique=True, verbose_name='No. HP Calon Siswa'),
        ),
    ]
