# Generated by Django 3.2.5 on 2021-08-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_participant_previous_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='info',
            field=models.CharField(choices=[('WEB', 'Website'), ('IG', 'Instagram'), ('FB', 'Facebook'), ('TW', 'Twitter'), ('TK', 'Tiktok'), ('SDR', 'Sodara/Keluarga'), ('ALK', 'Alumni SMK Telkom'), ('ALS', 'Alumni SMP'), ('GMP', 'Guru SMP'), ('GRK', 'Guru SMK'), ('BRS', 'Brosur'), ('RDO', 'Radio'), ('LLY', 'Lainnya')], max_length=3, null=True, verbose_name='Info Primaseru (PPDB)'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='previous_school',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Nama Asal Sekolah'),
        ),
    ]
