# Generated by Django 3.2.5 on 2021-08-14 05:37

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0022_auto_20210813_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantlms',
            name='time',
            field=models.CharField(max_length=20, verbose_name='Pukul'),
        ),
        migrations.CreateModel(
            name='ParticipantRePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=120, null=True, verbose_name='Pesan')),
                ('payment_1', models.FileField(upload_to=dashboard.models.user_directory_path, verbose_name='Pembayaran Ke 1')),
                ('verfied_1', models.BooleanField(default=False, verbose_name='Verifikasi Pembayaran 1')),
                ('comment_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Komentar Pembayaran 1')),
                ('payment_2', models.FileField(blank=True, null=True, upload_to=dashboard.models.user_directory_path, verbose_name='Pembayaran Ke 2')),
                ('verfied_2', models.BooleanField(default=False, verbose_name='Verifikasi Pembayaran 2')),
                ('comment_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Komentar Pembayaran 2')),
                ('payment_3', models.FileField(blank=True, null=True, upload_to=dashboard.models.user_directory_path, verbose_name='Pembayaran Ke 3')),
                ('verfied_3', models.BooleanField(default=False, verbose_name='Verifikasi Pembayaran 3')),
                ('comment_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Komentar Pembayaran 3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
