# Generated by Django 3.2.5 on 2021-08-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20210814_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantrepayment',
            name='deadline_1',
            field=models.DateField(null=True, verbose_name='Tengat Pembayaran Ke 1'),
        ),
        migrations.AddField(
            model_name='participantrepayment',
            name='deadline_2',
            field=models.DateField(null=True, verbose_name='Tengat Pembayaran Ke 2'),
        ),
        migrations.AddField(
            model_name='participantrepayment',
            name='deadline_3',
            field=models.DateField(null=True, verbose_name='Tengat Pembayaran Ke 3'),
        ),
    ]
