# Generated by Django 3.2.5 on 2021-08-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20210815_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantrepayment',
            name='deadline_1',
            field=models.DateField(blank=True, null=True, verbose_name='Tengat Pembayaran Ke 1'),
        ),
        migrations.AlterField(
            model_name='participantrepayment',
            name='deadline_2',
            field=models.DateField(blank=True, null=True, verbose_name='Tengat Pembayaran Ke 2'),
        ),
        migrations.AlterField(
            model_name='participantrepayment',
            name='deadline_3',
            field=models.DateField(blank=True, null=True, verbose_name='Tengat Pembayaran Ke 3'),
        ),
    ]
