# Generated by Django 3.2.5 on 2021-08-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20210818_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantrepayment',
            name='virt_acc_number',
            field=models.CharField(max_length=30, null=True, verbose_name='Nomor Virtual Account'),
        ),
    ]
