# Generated by Django 3.2.5 on 2021-08-21 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_participantrepayment_virt_acc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantgraduation',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
