# Generated by Django 3.2.5 on 2021-08-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_participantgraduation_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosourceppdb',
            name='info_source',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Sumber Info Primaseru'),
        ),
        migrations.AlterField(
            model_name='participantcount',
            name='count',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
