# Generated by Django 3.2.5 on 2021-08-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20210823_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantrepayment',
            name='paid_off',
            field=models.BooleanField(default=False, verbose_name='Lunas'),
        ),
    ]
