# Generated by Django 3.2.5 on 2021-08-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_participantrepayment_paid_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantrepayment',
            name='message',
        ),
        migrations.AlterField(
            model_name='participantrepayment',
            name='pay_mount_1',
            field=models.CharField(blank=True, help_text='Isi Dengan Angka Saja.', max_length=100, null=True, verbose_name='Nominal Pembayaran Ke 1'),
        ),
        migrations.AlterField(
            model_name='participantrepayment',
            name='pay_mount_2',
            field=models.CharField(blank=True, help_text='Isi Dengan Angka Saja.', max_length=100, null=True, verbose_name='Nominal Pembayaran Ke 2'),
        ),
        migrations.AlterField(
            model_name='participantrepayment',
            name='pay_mount_3',
            field=models.CharField(blank=True, help_text='Isi Dengan Angka Saja.', max_length=100, null=True, verbose_name='Nominal Pembayaran Ke 3'),
        ),
        migrations.AlterField(
            model_name='participantrepayment',
            name='virt_acc_number',
            field=models.CharField(help_text='Nomor Virtual Account Bank Mandiri atau CIMB Niaga.', max_length=30, null=True, verbose_name='Nomor Virtual Account'),
        ),
    ]
