# Generated by Django 3.2.5 on 2021-08-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_registerfileprimaseru_reregisterfileprimaseru'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rek_num', models.CharField(max_length=50, verbose_name='Nomor Rekening')),
                ('whom_rek', models.CharField(max_length=100, verbose_name='Rekening Atas Nama')),
                ('bank', models.CharField(max_length=100, verbose_name='Bank')),
                ('money', models.CharField(help_text='Isi hanya dengan angka.', max_length=7, verbose_name='Nominal Pembayaran')),
                ('wa_number', models.CharField(max_length=20, verbose_name='Nomor Whatsapp')),
                ('wa_link', models.CharField(max_length=100, verbose_name='Link Whatsapp')),
            ],
        ),
    ]
