# Generated by Django 3.2.5 on 2021-08-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_primaserucontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaserucontacts',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nama Kontak'),
        ),
    ]
