# Generated by Django 3.2.5 on 2021-08-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_primaserucontacts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbanner',
            name='sub_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Sub Judul'),
        ),
    ]
