# Generated by Django 3.2.5 on 2021-08-30 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_participant_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
