# Generated by Django 3.2.5 on 2021-08-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_participant_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
