# Generated by Django 3.2.5 on 2021-08-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_alter_participant_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='participantgraduation',
            options={'ordering': ['-participant']},
        ),
        migrations.AlterModelOptions(
            name='participantlms',
            options={'ordering': ['-participant']},
        ),
        migrations.AlterModelOptions(
            name='participantrepayment',
            options={'ordering': ['-participant']},
        ),
    ]
