# Generated by Django 3.2.5 on 2021-08-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20210830_0733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantgraduation',
            options={'ordering': ['participant']},
        ),
        migrations.AlterModelOptions(
            name='participantlms',
            options={'ordering': ['participant']},
        ),
        migrations.AlterModelOptions(
            name='participantrepayment',
            options={'ordering': ['participant']},
        ),
    ]
