# Generated by Django 3.2.5 on 2021-08-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20210830_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['account']},
        ),
    ]
