# Generated by Django 3.2.5 on 2021-08-31 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_alter_participant_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantrepayment',
            old_name='verfied_1',
            new_name='verified_1',
        ),
        migrations.RenameField(
            model_name='participantrepayment',
            old_name='verfied_2',
            new_name='verified_2',
        ),
        migrations.RenameField(
            model_name='participantrepayment',
            old_name='verfied_3',
            new_name='verified_3',
        ),
    ]
