# Generated by Django 3.2.5 on 2021-09-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20210831_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantcount',
            name='year',
            field=models.CharField(db_index=True, max_length=4, null=True, verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='participantcount',
            name='count',
            field=models.CharField(db_index=True, help_text='Mulai dari angka berapa, untuk nomor pendaftaran.', max_length=10, verbose_name='Hitungan'),
        ),
    ]
