# Generated by Django 3.2.5 on 2021-09-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_alter_participantcount_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantcount',
            name='count',
            field=models.CharField(db_index=True, help_text='     <ul>    <li> Mulai dari angka berapa, untuk nomor pendaftaran.</li>     <li> Tulis dengan 3 digit angka, contoh: 1 menjadi 001</li>     </ul>    ', max_length=10, verbose_name='Hitungan'),
        ),
    ]
