# Generated by Django 3.2.5 on 2021-09-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_alter_participantcount_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantgraduation',
            name='clock_accounce',
            field=models.TimeField(null=True, verbose_name='Jam Diumumkan'),
        ),
        migrations.AddField(
            model_name='participantgraduation',
            name='date_announce',
            field=models.DateField(null=True, verbose_name='Tanggal Diumumkan'),
        ),
    ]
