# Generated by Django 3.2.5 on 2021-09-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20210906_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantgraduation',
            old_name='clock_accounce',
            new_name='clock_announce',
        ),
    ]
