# Generated by Django 3.2.5 on 2021-09-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_rename_clock_accounce_participantgraduation_clock_announce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantgraduation',
            name='clock_announce',
            field=models.TimeField(help_text='Pukul berapa kelulusan diumumkan (WIB). Contoh: 08.00 atau 17.00', null=True, verbose_name='Jam Diumumkan'),
        ),
        migrations.AlterField(
            model_name='participantgraduation',
            name='date_announce',
            field=models.DateField(help_text='Tanggal berapa kelulusan akan diumumkan.', null=True, verbose_name='Tanggal Diumumkan'),
        ),
    ]
