# Generated by Django 3.2.5 on 2021-09-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_auto_20210910_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantrepayment',
            name='whom_acc',
            field=models.CharField(max_length=100, null=True, verbose_name='Virtual Account Atas Nama'),
        ),
    ]
