# Generated by Django 3.2.5 on 2021-09-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_participantrepayment_whom_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantgraduation',
            name='chose_major',
            field=models.CharField(blank=True, choices=[('TKJ', 'Teknik Komputer dan Jaringan'), ('TJAT', 'Teknik Jaringan Akses Telekomunikasi'), ('MM', 'Multimedia')], max_length=4, null=True, verbose_name='Diterima di Jurusan:'),
        ),
    ]
