# Generated by Django 3.2.11 on 2022-01-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_alter_participant_participant_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(choices=[('TKJ', 'Teknik Komputer dan Jaringan'), ('TJAT', 'Teknik Jaringan Akses Telekomunikasi'), ('MM', 'Multimedia')], max_length=4, verbose_name='Prodi')),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapasitan')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cap', models.PositiveIntegerField(verbose_name='Total kapasitas')),
            ],
        ),
    ]
