# Generated by Django 3.2.11 on 2022-02-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_majorcapacity_schoolcapacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nama Lengkap'),
        ),
    ]
