# Generated by Django 3.2.5 on 2022-02-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_alter_participant_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('ACT', 'Aktif'), ('RSG', 'Memundurkan Diri')], default='ACT', max_length=3, verbose_name='Status'),
        ),
    ]
