# Generated by Django 3.2.5 on 2022-04-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_participant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(help_text='Tulis singkatan jurusan, <b>contoh: TKJ</b>', max_length=5, verbose_name='Jurusan')),
                ('is_avail', models.BooleanField(verbose_name='Kuota Tersedia')),
            ],
        ),
    ]
