# Generated by Django 3.2.5 on 2022-04-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_majorstatus_major_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100, verbose_name='Jalur Pendaftaran')),
                ('is_avail', models.BooleanField(default=True, verbose_name='Jalur Masih Tersedia')),
            ],
        ),
    ]
