# Generated by Django 3.2.13 on 2022-07-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_registrationpath'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationPath',
        ),
        migrations.AddField(
            model_name='registerschedule',
            name='is_avail',
            field=models.BooleanField(default=True, verbose_name='Kuota Tersedia'),
        ),
        migrations.AlterField(
            model_name='registerschedule',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nama Gelombang/Jalur Pendaftaran'),
        ),
    ]
