# Generated by Django 3.2.13 on 2022-08-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_auto_20220725_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='reason_resign',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Alasan Memundurkan Diri'),
        ),
    ]
