# Generated by Django 3.2.13 on 2022-09-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_participant_reason_resign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorcapacity',
            name='major',
            field=models.CharField(choices=[('TJKT', 'Teknik Jaringan Komputer dan Telekomunikasi'), ('DKV', 'Desain Komunikasi & Visual'), ('Animasi', 'Animasi')], max_length=10, verbose_name='Prodi'),
        ),
        migrations.AlterField(
            model_name='participantgraduation',
            name='chose_major',
            field=models.CharField(blank=True, choices=[('TJKT', 'Teknik Jaringan Komputer dan Telekomunikasi'), ('DKV', 'Desain Komunikasi & Visual'), ('Animasi', 'Animasi')], max_length=10, null=True, verbose_name='Diterima di Jurusan:'),
        ),
    ]
