# Generated by Django 3.2.13 on 2022-11-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_auto_20220916_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantrepayment',
            name='comment_2',
        ),
        migrations.RemoveField(
            model_name='participantrepayment',
            name='comment_3',
        ),
        migrations.RemoveField(
            model_name='participantrepayment',
            name='deadline_2',
        ),
        migrations.RemoveField(
            model_name='participantrepayment',
            name='deadline_3',
        ),
        migrations.RemoveField(
            model_name='participantrepayment',
            name='pay_mount_2',
        ),
        migrations.RemoveField(
            model_name='participantrepayment',
            name='pay_mount_3',
        ),
        migrations.RemoveField(
            model_name='participantrepayment',
            name='payment_2',
        ),
        migrations.RemoveField(
            model_name='participantrepayment',
            name='payment_3',
        ),
        migrations.RemoveField(
            model_name='participantrepayment',
            name='verified_2',
        ),
        migrations.RemoveField(
            model_name='participantrepayment',
            name='verified_3',
        ),
        migrations.AlterField(
            model_name='majorcapacity',
            name='major',
            field=models.CharField(choices=[('TJKT', 'Teknik Jaringan Komputer dan Telekomunikasi'), ('DKV', 'Desain Komunikasi & Visual'), ('ANI', 'Animasi')], max_length=10, verbose_name='Prodi'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Centang jika telah membayar biaya Pendaftaran.', verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='participantgraduation',
            name='chose_major',
            field=models.CharField(blank=True, choices=[('TJKT', 'Teknik Jaringan Komputer dan Telekomunikasi'), ('DKV', 'Desain Komunikasi & Visual'), ('ANI', 'Animasi')], max_length=10, null=True, verbose_name='Diterima di Jurusan:'),
        ),
    ]
