# Generated by Django 3.2.5 on 2021-07-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nama Gelombang Pendaftaran')),
                ('start_date', models.DateField(verbose_name='Tanggal Dimulai Pendaftaran')),
                ('end_date', models.DateField(verbose_name='Tanggal Berakhir Pendaftaran')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100, verbose_name='Langkap Pendaftaran')),
                ('icon', models.ImageField(upload_to='register_step_icon', verbose_name='Icon')),
            ],
        ),
    ]
