# Generated by Django 3.2.5 on 2021-07-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterSchedule',
        ),
        migrations.DeleteModel(
            name='RegisterStep',
        ),
    ]
