# Generated by Django 3.2.11 on 2022-02-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_filespool'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProsTelkomBandung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='homepage_icon/', verbose_name='Gambar (Icon)')),
                ('desc', models.TextField(verbose_name='Deskripsi')),
            ],
        ),
    ]
